/*
**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void vMainLEDTask1(void *pvparam){
	while(1){
	LedToggle(LED_GREEN_PIN);
	vTaskDelay(1000/portTICK_RATE_MS);
	}
	vTaskDelete(NULL);

}
void vMainLEDTask2(void *pvparam){
	while(1){
	LedToggle(LED_ORANGE_PIN);
	vTaskDelay(1000/portTICK_RATE_MS);
		}
		vTaskDelete(NULL);
}
void vMainLEDTask3(void *pvparam){
	while(1){

	LedToggle(LED_RED_PIN);
	vTaskDelay(1000/portTICK_RATE_MS);
		}
		vTaskDelete(NULL);
}
void vMainLEDTask4(void *pvparam){
	while(1){

	LedToggle(LED_BLUE_PIN);
	vTaskDelay(1000/portTICK_RATE_MS);
		}
		vTaskDelete(NULL);
}


int main(void){
	LedInit(LED_GREEN_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	xTaskCreate(vMainLEDTask1, "led1", configMINIMAL_STACK_SIZE,NULL, 4, NULL);
	xTaskCreate(vMainLEDTask2, "led1", configMINIMAL_STACK_SIZE,NULL, 4, NULL);
	xTaskCreate(vMainLEDTask3, "led1", configMINIMAL_STACK_SIZE,NULL, 4, NULL);
	xTaskCreate(vMainLEDTask4, "led1", configMINIMAL_STACK_SIZE,NULL, 4, NULL);

	vTaskStartScheduler();
	while(1);


}










