/*
**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include"FreeRTOS.h"
#include"FreeRTOSConfig.h"
#include"task.h"
#include"led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
struct param{
	int pin;
	int delay;
};
void vMainLEDTask1(void *pvparam){
	struct param* ptr=(struct param*)pvparam;
	portTickType xLastWakeuptime;

	while(1){
	LedToggle(ptr->pin);
	xLastWakeuptime = xTaskGetTickCount();
	vTaskDelayUntil(&xLastWakeuptime, ptr->delay/ portTICK_RATE_MS);
	}
	vTaskDelete(NULL);

}

int main(void){
	LedInit(LED_GREEN_PIN);
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
	LedInit(LED_BLUE_PIN);
	struct param p1;



	p1.pin=LED_GREEN_PIN;
	p1.delay=1000;

	struct param p2;
		p2.pin=LED_ORANGE_PIN;
		p2.delay=1000;


		struct param p3;
		p3.pin=LED_RED_PIN;
		p3.delay=1000;


		struct param p4;
		p4.pin=LED_BLUE_PIN;
		p4.delay=1000;
	xTaskCreate(vMainLEDTask1, "led1", configMINIMAL_STACK_SIZE,&p1, 4, NULL);
	xTaskCreate(vMainLEDTask1, "led2", configMINIMAL_STACK_SIZE,&p2, 4, NULL);
	xTaskCreate(vMainLEDTask1, "led3", configMINIMAL_STACK_SIZE,&p3, 4, NULL);
	xTaskCreate(vMainLEDTask1, "led4", configMINIMAL_STACK_SIZE,&p4, 4, NULL);

	vTaskStartScheduler();
	while(1);


}










